//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjPropertyRentalManagementWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Apartment
    {
        public string ApartmentID { get; set; }
        public string BuildingID { get; set; }
        public string OwnerID { get; set; }
        public string ManagerID { get; set; }
        public string TenentID { get; set; }
        public string AoartmentNumber { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<short> Bedrooms { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual Manager Manager { get; set; }
        public virtual Owner Owner { get; set; }
        public virtual Tenent Tenent { get; set; }
    }
}
