//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrjPropertyRentalManagementWebSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public string AppointmentID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public string Status { get; set; }
        public string ScheduleID { get; set; }
        public string ManagerID { get; set; }
        public string Username { get; set; }
    
        public virtual Manager Manager { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
